import type { ExerciseContent } from "@/lib/types";

/**
 * Original Good Dog exercise library.
 * Independent content — not affiliated with or endorsed by any training organisation.
 */
export const EXERCISE_LIBRARY: ExerciseContent[] = [
  {
    id: "ex-name-response",
    slug: "practise-responding-to-name",
    title: "Practise responding to their name",
    summary: "Help your dog learn that looking towards you is worthwhile.",
    learningObjectiveId: "name-response",
    category: "engagement",
    lifeStages: [
      "young_puppy",
      "older_puppy",
      "adolescent",
      "adult",
      "senior",
    ],
    difficulty: 1,
    estimatedMinutes: 2,
    prerequisiteIds: [],
    purpose:
      "Help your dog learn that turning towards you when they hear their name is worthwhile. This is everyday [[positive-reinforcement|positive reinforcement]]: a valued reward follows the look, so looking becomes more likely.",
    preparation:
      "Choose a quiet room. Have a few small pieces of food your dog enjoys, or another suitable [[reward]].",
    steps: [
      "Wait until your dog is not already looking at you.",
      "Say their name once in a friendly voice. Their name is the [[cue]] for checking in.",
      "When they turn towards you, say “Yes!” — your [[marker-word]] — then give a reward. Good [[timing]] marks the glance, not what happens afterwards.",
      "Repeat a few times, allowing short breaks.",
    ],
    lookFor: "Your dog starts turning towards you more readily.",
    ifDifficult:
      "Move somewhere quieter, reduce distractions, and make the exercise easier. Avoid repeating their name over and over. If they seem worried, you may be past a comfortable [[threshold]] — give more space.",
    harderVariationId: "ex-name-mild-distract",
    hint: "Say the name once, then wait. Quiet patience often works better than repeating.",
    glossaryTermIds: [
      "positive-reinforcement",
      "reward",
      "cue",
      "marker-word",
      "timing",
      "threshold",
    ],
    topicGroup: "everyday_foundations",
    contentVersion: 2,
  },
  {
    id: "ex-reward-marker",
    slug: "introduce-a-yes-word",
    title: "Introduce a friendly ‘yes’ word",
    summary: "Teach a simple word that means a reward is coming.",
    learningObjectiveId: "reward-marker",
    category: "engagement",
    lifeStages: [
      "young_puppy",
      "older_puppy",
      "adolescent",
      "adult",
      "senior",
    ],
    difficulty: 1,
    estimatedMinutes: 2,
    prerequisiteIds: [],
    purpose:
      "Give yourself a clear way to mark the exact moment your dog does something useful. Trainers call this an [[event-marker]]. Today you’ll use a spoken [[marker-word]].",
    preparation:
      "Have several tiny treats ready for clear [[reward-delivery]]. Practise somewhere calm with few distractions.",
    steps: [
      "Say “Yes!” in a bright, consistent tone. You may hear trainers call this a [[marker-word]].",
      "Immediately follow with a small [[reward]]. The marker identifies the moment; the reward pays for it.",
      "Repeat a handful of times with short pauses. Aim for crisp [[timing]] — marker, then reward.",
      "Later, use the same word the moment your dog offers something you like ([[capturing]] a behaviour).",
    ],
    lookFor: "Your dog starts looking hopeful as soon as they hear the word.",
    ifDifficult:
      "Keep sessions very short and use a reward your dog clearly enjoys. If they get frantic, pause — [[arousal]] may be too high for clear learning.",
    hint: "The word should come first, then the reward — keep the gap tiny.",
    glossaryTermIds: [
      "event-marker",
      "marker-word",
      "reward",
      "reward-delivery",
      "timing",
      "capturing",
      "arousal",
    ],
    topicGroup: "everyday_foundations",
    contentVersion: 2,
  },
  {
    id: "ex-engagement-easy",
    slug: "invite-attention",
    title: "Invite a moment of attention",
    summary: "A short, easy way to start a session together.",
    learningObjectiveId: "engagement",
    category: "engagement",
    lifeStages: [
      "young_puppy",
      "older_puppy",
      "adolescent",
      "adult",
      "senior",
    ],
    difficulty: 1,
    estimatedMinutes: 2,
    prerequisiteIds: [],
    purpose:
      "Warm up by encouraging your dog to notice you and choose to engage. You may hear trainers call this [[engagement|focus or engagement]].",
    preparation:
      "Stand or sit somewhere quiet. Have a couple of rewards ready — whatever acts as a [[reinforcer]] for your dog today.",
    steps: [
      "Make a gentle sound or show a reward near your chest.",
      "When your dog looks at you, use your [[marker-word]] and reward. This is [[capturing]] a glance.",
      "Take a small step sideways and wait for another look.",
      "Finish while it still feels easy and friendly.",
    ],
    lookFor: "Willing glances and a relaxed posture.",
    ifDifficult:
      "Move closer, reduce noise, and reward any glance in your direction. Lower your [[criteria]] rather than insisting.",
    hint: "You are inviting, not insisting. Keep it light.",
    glossaryTermIds: [
      "engagement",
      "reinforcer",
      "marker-word",
      "capturing",
      "criteria",
    ],
    topicGroup: "everyday_foundations",
    contentVersion: 2,
  },
  {
    id: "ex-sit-comfort",
    slug: "comfortable-sit",
    title: "Teach a comfortable sit",
    summary: "Help your dog sit in a way that feels easy and natural.",
    learningObjectiveId: "sit",
    category: "manners",
    lifeStages: [
      "young_puppy",
      "older_puppy",
      "adolescent",
      "adult",
      "senior",
    ],
    difficulty: 1,
    estimatedMinutes: 3,
    prerequisiteIds: ["ex-engagement-easy"],
    purpose:
      "Build a simple sit that your dog can offer without being pushed into position. We’ll use gentle [[luring]] to guide the movement.",
    preparation:
      "Use a non-slippery floor. Have treats ready at your dog’s nose height for [[luring]].",
    steps: [
      "Hold a treat near your dog’s nose — this starts the lure.",
      "Slowly move it up and slightly back over their head ([[luring]] into a sit).",
      "As their bottom lowers, say your [[marker-word]] and reward. That [[timing]] pays for the sit.",
      "Repeat a few times, then pause before they get tired. Later you can add a verbal [[cue]] once the sit is easy.",
    ],
    lookFor: "A soft, willing sit without wobbling or worry — early [[fluency]].",
    ifDifficult:
      "Ask for a smaller movement, reward sooner, or practise on a more secure surface. That means lowering your [[criteria]].",
    safetyNote:
      "If sitting seems stiff or painful, stop and speak to your vet before continuing.",
    harderVariationId: "ex-wait-brief",
    hint: "Lure slowly. Rushing often makes dogs jump instead of sit.",
    glossaryTermIds: ["luring", "marker-word", "timing", "cue", "fluency", "criteria"],
    topicGroup: "everyday_foundations",
    contentVersion: 2,
  },
  {
    id: "ex-wait-brief",
    slug: "brief-wait",
    title: "Practise a brief wait",
    summary: "Build a short pause before moving on.",
    learningObjectiveId: "wait",
    category: "manners",
    lifeStages: ["older_puppy", "adolescent", "adult", "senior"],
    difficulty: 2,
    estimatedMinutes: 3,
    prerequisiteIds: ["ex-sit-comfort"],
    purpose:
      "Help your dog pause calmly for a moment before moving on. Trainers often call this a brief [[wait]].",
    preparation: "Start indoors. Have a reward ready and keep sessions short.",
    steps: [
      "Ask for a sit, or wait until your dog sits.",
      "Hold a flat hand briefly as a pause [[cue]].",
      "Count one second, then use your [[marker-word]] and reward while they are still waiting.",
      "Release with a cheerful word such as “okay” and take a step together.",
    ],
    lookFor: "A relaxed pause without leaping up early — early [[fluency]], not a long stare-down.",
    ifDifficult:
      "Reward after half a second, then gradually build. That means lowering your [[criteria]].",
    easierVariationId: "ex-sit-comfort",
    hint: "Short successful waits beat long, wobbly ones.",
    glossaryTermIds: ["wait", "cue", "marker-word", "fluency", "criteria"],
    topicGroup: "life_at_home",
    contentVersion: 2,
  },
  {
    id: "ex-mat-settle",
    slug: "settle-on-a-mat",
    title: "Settle on a mat",
    summary: "Show your dog that a mat is a calm, rewarding place.",
    learningObjectiveId: "mat-settle",
    category: "calm",
    lifeStages: [
      "young_puppy",
      "older_puppy",
      "adolescent",
      "adult",
      "senior",
    ],
    difficulty: 1,
    estimatedMinutes: 3,
    prerequisiteIds: [],
    purpose:
      "Give your dog a clear place to [[settle]], useful for busy moments at home. We’ll build it with [[shaping]] — rewarding small steps towards lying calmly on the mat.",
    preparation:
      "Place a mat or towel on the floor in a quiet spot. Have soft rewards ready.",
    steps: [
      "Toss a treat onto the mat and let your dog step on to eat it. Approaching can be your first [[criteria]].",
      "Use your [[marker-word]] for any feet on the mat and reward on the mat.",
      "If they lie down, mark and reward calmly — a bigger step in the [[shaping]] plan.",
      "Keep early sessions short and end before they wander off.",
    ],
    lookFor: "Willing approaches to the mat and softer [[body-language]].",
    ifDifficult:
      "Make the mat more inviting with easier rewards and less pressure to stay. Lower the [[criteria]].",
    harderVariationId: "ex-calm-home",
    hint: "Reward on the mat itself so the place becomes valuable.",
    glossaryTermIds: [
      "settle",
      "shaping",
      "criteria",
      "marker-word",
      "body-language",
    ],
    topicGroup: "calm_confidence",
    contentVersion: 2,
  },
  {
    id: "ex-calm-home",
    slug: "calm-settle-at-home",
    title: "Practise calm settling at home",
    summary: "Build quiet moments into ordinary household life.",
    learningObjectiveId: "calm-home",
    category: "calm",
    lifeStages: ["older_puppy", "adolescent", "adult", "senior"],
    difficulty: 2,
    estimatedMinutes: 3,
    prerequisiteIds: ["ex-mat-settle"],
    purpose:
      "Help your dog practise a calm [[settle]] while everyday life continues nearby — gentle [[generalisation]] of the mat skill.",
    preparation:
      "Use the mat your dog already knows. Start when the house is fairly quiet so [[arousal]] stays manageable.",
    steps: [
      "Invite your dog to the mat and reward a [[settle]].",
      "Sit nearby and calmly read or sip a drink for a minute.",
      "Quietly reward soft staying every so often — keep [[criteria]] realistic.",
      "Release gently and finish before they get restless. Allow [[recovery-time]] afterwards if needed.",
    ],
    lookFor: "Softer breathing and a willingness to stay without fussing. Watch [[body-language]].",
    ifDifficult:
      "Shorten the time, reduce household movement, and return to simpler mat rewards.",
    easierVariationId: "ex-mat-settle",
    hint: "Calm owner energy helps. Avoid excitedly chatting through the settle.",
    glossaryTermIds: [
      "settle",
      "generalisation",
      "arousal",
      "criteria",
      "recovery-time",
      "body-language",
    ],
    topicGroup: "calm_confidence",
    contentVersion: 2,
  },
  {
    id: "ex-handling-touch",
    slug: "gentle-handling",
    title: "Build comfortable handling",
    summary: "Help your dog feel safe with gentle everyday touch.",
    learningObjectiveId: "handling",
    category: "confidence",
    lifeStages: [
      "young_puppy",
      "older_puppy",
      "adolescent",
      "adult",
      "senior",
    ],
    difficulty: 1,
    estimatedMinutes: 3,
    prerequisiteIds: [],
    purpose:
      "Make collar touches, ear checks, and gentle handling feel predictable and kind. This supports [[choice-consent|choice and consent in handling]].",
    preparation:
      "Choose a quiet spot. Have high-value rewards. Keep your movements slow.",
    steps: [
      "Touch a neutral area such as the shoulder for one second.",
      "Use your [[marker-word]] and reward immediately.",
      "Repeat with brief touches to collar area, then paws if comfortable.",
      "Stop while your dog still looks relaxed — watch their [[body-language]].",
    ],
    lookFor: "Soft eyes, loose body, and willingness to stay near you. Notice [[stress-signals]] such as freezing or turning away.",
    ifDifficult:
      "Touch even more briefly, use better rewards, and avoid areas your dog finds tricky.",
    safetyNote:
      "If your dog flinches, freezes, growls, or tries to move away, stop. Do not force handling.",
    hint: "Touch, then reward. Never pin or restrain for this exercise.",
    glossaryTermIds: [
      "choice-consent",
      "marker-word",
      "body-language",
      "stress-signals",
    ],
    topicGroup: "calm_confidence",
    contentVersion: 2,
  },
  {
    id: "ex-name-mild-distract",
    slug: "name-with-mild-distraction",
    title: "Name response with a mild distraction",
    summary: "Practise checking in when something else is nearby.",
    learningObjectiveId: "name-response",
    category: "engagement",
    lifeStages: ["older_puppy", "adolescent", "adult", "senior"],
    difficulty: 2,
    estimatedMinutes: 3,
    prerequisiteIds: ["ex-name-response"],
    purpose:
      "Strengthen name response when the environment is a little more interesting. This is gentle [[proofing]] / [[generalisation]] — the same skill in a slightly harder picture.",
    preparation:
      "Start in a familiar room with a mild [[trigger|distraction]], such as a toy on the floor.",
    steps: [
      "Wait until your dog notices the mild distraction.",
      "Say their name once — one clear [[cue]].",
      "If they turn to you, use your [[marker-word]] and reward generously.",
      "If not, move a little closer or make the distraction quieter, then try again. Extra [[distance]] from the distraction often helps.",
    ],
    lookFor: "Turning to you even when something else is present.",
    ifDifficult:
      "Return to quiet name practice, then add distraction more gradually. If they cannot respond comfortably, you may be past a practical [[threshold]] — make it easier.",
    easierVariationId: "ex-name-response",
    harderVariationId: "ex-recall-foundation",
    hint: "One clear name cue. If they miss it, change the setup rather than repeating loudly.",
    glossaryTermIds: [
      "proofing",
      "generalisation",
      "trigger",
      "cue",
      "marker-word",
      "distance",
      "threshold",
    ],
    topicGroup: "everyday_foundations",
    contentVersion: 2,
  },
  {
    id: "ex-recall-foundation",
    slug: "recall-foundations",
    title: "Build a recall foundation",
    summary: "Make coming back to you feel brilliant.",
    learningObjectiveId: "recall",
    category: "recall",
    lifeStages: [
      "young_puppy",
      "older_puppy",
      "adolescent",
      "adult",
      "senior",
    ],
    difficulty: 2,
    estimatedMinutes: 3,
    prerequisiteIds: ["ex-name-response"],
    purpose:
      "Teach a [[recall]] — coming towards you when invited — so return feels like one of the best choices available.",
    preparation:
      "Use a hallway or quiet garden. Have excellent rewards. Keep a long line if outdoors ([[management]] for safety while you train).",
    steps: [
      "Crouch slightly and use a cheerful recall [[cue]] once.",
      "As your dog moves towards you, encourage warmly.",
      "When they arrive, use your [[marker-word]] and give several small rewards ([[positive-reinforcement]]).",
      "Release them to sniff again so coming back does not end the fun.",
    ],
    lookFor: "Willing movement towards you without hesitation.",
    ifDifficult:
      "Start closer, use better rewards, and practise before [[arousal]] gets high.",
    safetyNote:
      "Do not practise off-lead near roads or unfenced hazards until your dog is ready.",
    easierVariationId: "ex-name-response",
    harderVariationId: "ex-recall-mild-distract",
    hint: "Reward arrival generously. Coming back should feel like a celebration.",
    glossaryTermIds: [
      "recall",
      "management",
      "cue",
      "marker-word",
      "positive-reinforcement",
      "arousal",
    ],
    topicGroup: "coming_back",
    contentVersion: 2,
  },
  {
    id: "ex-recall-mild-distract",
    slug: "recall-with-mild-distraction",
    title: "Recall with a mild distraction",
    summary: "Practise coming back when something else is mildly interesting.",
    learningObjectiveId: "recall",
    category: "recall",
    lifeStages: ["older_puppy", "adolescent", "adult", "senior"],
    difficulty: 3,
    estimatedMinutes: 4,
    prerequisiteIds: ["ex-recall-foundation"],
    purpose:
      "Strengthen [[recall]] when your dog has a mild competing interest — careful [[proofing]], not a hard test.",
    preparation:
      "Quiet outdoor space or large room. Use a long line for safety outdoors ([[management]]).",
    steps: [
      "Allow a brief sniff or glance at a mild distraction.",
      "Give your recall [[cue]] once in a friendly voice.",
      "[[Reward]] heavily for coming away and returning.",
      "Keep success easy — [[distance]] and distraction should still feel under a comfortable [[threshold]].",
    ],
    lookFor: "Turning away from the distraction and returning willingly.",
    ifDifficult:
      "Reduce distance, choose a quieter spot, or return to easier recall games. Lower the [[criteria]].",
    easierVariationId: "ex-recall-foundation",
    safetyNote:
      "If your dog becomes overwhelmed or overexcited, pause and simplify. Use a lead or long line.",
    hint: "Set them up to succeed. Hard recalls learnt through failure take longer to repair.",
    glossaryTermIds: [
      "recall",
      "proofing",
      "management",
      "cue",
      "reward",
      "distance",
      "threshold",
      "criteria",
    ],
    topicGroup: "coming_back",
    contentVersion: 2,
  },
  {
    id: "ex-lead-intro",
    slug: "friendly-lead-introduction",
    title: "Make the lead feel friendly",
    summary: "Help your dog feel comfortable wearing and moving on a lead.",
    learningObjectiveId: "lead-walking",
    category: "walking",
    lifeStages: [
      "young_puppy",
      "older_puppy",
      "adolescent",
      "adult",
      "senior",
    ],
    difficulty: 1,
    estimatedMinutes: 3,
    prerequisiteIds: [],
    purpose:
      "Build positive feelings about the harness or collar and a light lead — a kind foundation for later [[loose-lead-walking]].",
    preparation:
      "Use a well-fitting harness if possible. Practise indoors first. Support [[choice-consent]] by going slowly.",
    steps: [
      "Present the harness or collar and [[reward]] curiosity.",
      "Put it on gently, then reward and remove before fuss builds. Watch [[body-language]].",
      "Clip on a light lead and take a few steps indoors, rewarding calm movement.",
      "Keep the session short and end on a success. Allow [[recovery-time]] if your dog seemed tense.",
    ],
    lookFor: "Relaxed [[body-language]] while kitted up.",
    ifDifficult:
      "Go slower, pair each step with food, and practise for seconds rather than minutes. Lower the [[criteria]].",
    safetyNote:
      "Avoid tight collars that dig in, and never use equipment designed to cause pain or fear.",
    harderVariationId: "ex-lead-loose",
    hint: "The kit should predict good things, not the start of a battle.",
    glossaryTermIds: [
      "loose-lead-walking",
      "choice-consent",
      "reward",
      "body-language",
      "recovery-time",
      "criteria",
    ],
    topicGroup: "walking_together",
    contentVersion: 2,
  },
  {
    id: "ex-lead-loose",
    slug: "loose-lead-foundations",
    title: "Loose-lead walking foundations",
    summary: "Reward walking near you with a soft lead.",
    learningObjectiveId: "lead-walking",
    category: "walking",
    lifeStages: ["older_puppy", "adolescent", "adult", "senior"],
    difficulty: 2,
    estimatedMinutes: 4,
    prerequisiteIds: ["ex-lead-intro"],
    purpose:
      "Build [[loose-lead-walking]] by paying generously when the lead stays soft.",
    preparation:
      "Start in a quiet indoor space or empty car park. Have treats accessible. Choose a place where [[arousal]] can stay moderate.",
    steps: [
      "Begin walking and use your [[marker-word]] for any moment the lead is soft.",
      "[[Reward]] by your side — soft lead earns good things ([[positive-reinforcement]]).",
      "If the lead tightens, stop politely and wait for slack, then move on.",
      "Keep sessions short — a few good metres beat a long struggle.",
    ],
    lookFor: "More frequent soft-lead moments and checking in with you.",
    ifDifficult:
      "Practise in a quieter place, reward more often, and shorten the walk segment.",
    easierVariationId: "ex-lead-intro",
    harderVariationId: "ex-check-in-walk",
    safetyNote:
      "Do not jerk the lead or use aversive equipment. If walks feel unsafe, seek local reward-based help.",
    hint: "Reward the lead when it is soft. Stopping is clearer than tugging.",
    glossaryTermIds: [
      "loose-lead-walking",
      "arousal",
      "marker-word",
      "reward",
      "positive-reinforcement",
    ],
    topicGroup: "walking_together",
    contentVersion: 2,
  },
  {
    id: "ex-check-in-walk",
    slug: "check-ins-on-walks",
    title: "Practise check-ins on walks",
    summary: "Reward your dog for glancing back to you outdoors.",
    learningObjectiveId: "check-in",
    category: "walking",
    lifeStages: ["older_puppy", "adolescent", "adult", "senior"],
    difficulty: 2,
    estimatedMinutes: 3,
    prerequisiteIds: ["ex-name-response", "ex-lead-intro"],
    purpose:
      "Make voluntarily checking in with you a habit on ordinary walks — outdoor [[engagement]] and light [[generalisation]].",
    preparation:
      "Choose a familiar, fairly quiet walking route. Keep rewards handy. Stay under a comfortable [[threshold]].",
    steps: [
      "Walk normally and watch for any glance towards you ([[capturing]]).",
      "Use your [[marker-word]] and reward those check-ins.",
      "Occasionally say their name once if needed, then reward the turn — that name is a [[cue]].",
      "Keep it conversational — a few good check-ins is enough.",
    ],
    lookFor: "More frequent voluntary looks back to you.",
    ifDifficult:
      "Use a quieter route and reward even tiny head turns in your direction. Lower the [[criteria]].",
    easierVariationId: "ex-name-response",
    hint: "Catch the check-in early. You are paying for attention, not waiting for perfection.",
    glossaryTermIds: [
      "engagement",
      "generalisation",
      "threshold",
      "capturing",
      "marker-word",
      "cue",
      "criteria",
    ],
    topicGroup: "walking_together",
    contentVersion: 2,
  },
  {
    id: "ex-leave-it-easy",
    slug: "easy-leave-it",
    title: "Easy ‘leave it’ game",
    summary: "Practise turning away from a mildly interesting item.",
    learningObjectiveId: "leave-it",
    category: "manners",
    lifeStages: ["older_puppy", "adolescent", "adult", "senior"],
    difficulty: 2,
    estimatedMinutes: 3,
    prerequisiteIds: ["ex-engagement-easy"],
    purpose:
      "Practise an easy [[leave-it]] game: turning away from something can earn something better.",
    preparation:
      "Use a low-value item under your foot or hand, and higher-value rewards from your other hand. Dangerous items are a [[management]] job first — not a training game.",
    steps: [
      "Place a dull item where your dog can see but not take it.",
      "Wait for any look away or pause — that is today’s [[criteria]].",
      "Use your [[marker-word]] and reward from your other hand.",
      "Repeat a few times, keeping success easy.",
    ],
    lookFor: "Offering space from the item without tension. Watch [[body-language]].",
    ifDifficult:
      "Use an even duller item and reward the tiniest look away.",
    safetyNote:
      "Do not use this game with dangerous items your dog might grab. Manage first, train second.",
    hint: "You are teaching a choice, not a stare-down.",
    glossaryTermIds: [
      "leave-it",
      "management",
      "criteria",
      "marker-word",
      "body-language",
    ],
    topicGroup: "life_at_home",
    contentVersion: 2,
  },
  {
    id: "ex-door-manners",
    slug: "calm-at-the-door",
    title: "Calm moments at the door",
    summary: "Practise pausing calmly near a doorway.",
    learningObjectiveId: "door-manners",
    category: "manners",
    lifeStages: ["older_puppy", "adolescent", "adult", "senior"],
    difficulty: 2,
    estimatedMinutes: 3,
    prerequisiteIds: ["ex-wait-brief"],
    purpose:
      "Make doorways less exciting so exits feel safer and calmer. This is everyday [[door-manners]], built from a brief [[wait]] plus [[management]].",
    preparation:
      "Practise at an internal door first. Have rewards ready. Keep [[arousal]] low.",
    steps: [
      "Approach the closed door together.",
      "Ask for a brief [[wait]] or reward any calm feet-still moment.",
      "Open the door a little, use your [[marker-word]] for calm, then close and reward.",
      "Only move through once calm feels easy.",
    ],
    lookFor: "Less rushing and more settled feet near the door.",
    ifDifficult:
      "Practise further from the door and keep openings tiny. Increase [[distance]] from the excitement.",
    easierVariationId: "ex-wait-brief",
    hint: "The door opening is a privilege earned by calm, not a race start.",
    glossaryTermIds: [
      "door-manners",
      "wait",
      "management",
      "arousal",
      "marker-word",
      "distance",
    ],
    topicGroup: "life_at_home",
    contentVersion: 2,
  },
  {
    id: "ex-greeting-calm",
    slug: "calmer-greetings",
    title: "Practise calmer greetings",
    summary: "Help your dog greet people with softer energy.",
    learningObjectiveId: "greetings",
    category: "manners",
    lifeStages: ["older_puppy", "adolescent", "adult", "senior"],
    difficulty: 2,
    estimatedMinutes: 3,
    prerequisiteIds: ["ex-sit-comfort"],
    purpose:
      "Teach that calm approaches earn attention, while jumping gets a gentle reset. Use [[management]] and clear [[criteria]], not confrontation.",
    preparation:
      "Ask a helper to approach slowly. Have treats ready. Keep greetings short so [[arousal]] does not spike.",
    steps: [
      "Helper approaches without excited talk.",
      "If your dog keeps paws down, use your [[marker-word]] and allow a brief hello.",
      "If they jump, helper calmly steps back and waits ([[management]]).",
      "Reward the next calm moment and end before overexcitement builds. Allow [[recovery-time]] if needed.",
    ],
    lookFor: "More four-paws-on-floor greetings. Soft [[body-language]] beats a stiff “sit” under pressure.",
    ifDifficult:
      "Greet at a greater [[distance]], keep visits shorter, and reward calmer earlier signs.",
    safetyNote:
      "If greeting involves snapping, lunging, or serious worry, stop and seek qualified reward-based help.",
    hint: "Attention is the reward. Jumping should pause the greeting, not create a scuffle.",
    glossaryTermIds: [
      "management",
      "criteria",
      "arousal",
      "marker-word",
      "recovery-time",
      "body-language",
      "distance",
    ],
    topicGroup: "life_at_home",
    contentVersion: 2,
  },
  {
    id: "ex-rest-spot",
    slug: "quiet-rest-spot",
    title: "Build a quiet rest spot",
    summary: "Help your dog enjoy a predictable place to settle.",
    learningObjectiveId: "rest-spot",
    category: "calm",
    lifeStages: [
      "young_puppy",
      "older_puppy",
      "adolescent",
      "adult",
      "senior",
    ],
    difficulty: 1,
    estimatedMinutes: 3,
    prerequisiteIds: [],
    purpose:
      "Create a rest place that predicts calm rewards and quiet time — a soft form of [[enrichment]] and a calm [[settle]] option.",
    preparation:
      "Choose a bed, crate with door open, or corner mat. Never force confinement; support [[choice-consent]].",
    steps: [
      "Toss a few treats onto the rest spot.",
      "[[Reward]] your dog for going there voluntarily ([[capturing]]).",
      "Sit nearby for a short calm minute.",
      "Allow free exit — the spot should feel optional and safe.",
    ],
    lookFor: "Willing visits and softer settling. Soft [[body-language]].",
    ifDifficult:
      "Use better treats, shorter stays, and keep the area open and inviting.",
    safetyNote:
      "Do not shut a worried dog in a crate for this exercise. Rest places should feel safe.",
    hint: "Optional beats forced. A rest spot works when the dog chooses it.",
    glossaryTermIds: [
      "enrichment",
      "settle",
      "choice-consent",
      "reward",
      "capturing",
      "body-language",
    ],
    topicGroup: "calm_confidence",
    contentVersion: 2,
  },
  {
    id: "ex-puppy-sounds",
    slug: "puppy-everyday-sounds",
    title: "Get used to everyday sounds",
    summary: "Gently introduce ordinary household noises.",
    learningObjectiveId: "puppy-confidence",
    category: "puppy",
    lifeStages: ["young_puppy", "older_puppy"],
    difficulty: 1,
    estimatedMinutes: 3,
    prerequisiteIds: [],
    purpose:
      "Help a puppy feel more confident about normal home sounds at a comfortable [[distance]]. You may hear related ideas called [[desensitisation]] and [[counterconditioning]] — we keep this gentle and optional.",
    preparation:
      "Stay far enough away that the sound is mild (below a practical [[threshold]]). Have tasty rewards ready.",
    steps: [
      "Play a quiet everyday sound (kettle, distant traffic recording, soft doorbell).",
      "As soon as it starts, scatter a few treats on the floor so the sound predicts good news.",
      "Keep the volume low and the session short.",
      "Stop if your puppy looks worried — notice [[stress-signals]]. Quieter and further is better.",
    ],
    lookFor: "Curious or neutral responses rather than startling or hiding.",
    ifDifficult:
      "Turn the sound down, increase [[distance]], and pair with easier rewards. Never push through fear.",
    safetyNote:
      "Never force a puppy to stay near a scary sound. Fear needs space and time. Serious fear needs qualified in-person help — this app is not a treatment plan.",
    hint: "Sound predicts snacks. Keep it boringly gentle.",
    glossaryTermIds: [
      "distance",
      "desensitisation",
      "counterconditioning",
      "threshold",
      "stress-signals",
    ],
    topicGroup: "puppy_life",
    contentVersion: 2,
  },
  {
    id: "ex-puppy-surfaces",
    slug: "puppy-different-surfaces",
    title: "Explore different surfaces",
    summary: "Help your puppy feel confident on varied ground.",
    learningObjectiveId: "puppy-confidence",
    category: "puppy",
    lifeStages: ["young_puppy", "older_puppy"],
    difficulty: 1,
    estimatedMinutes: 3,
    prerequisiteIds: [],
    purpose:
      "Build confidence on grass, rubber mats, or other safe everyday surfaces — gentle exploration with [[choice-consent]].",
    preparation:
      "Choose two safe surfaces. Keep sessions playful and optional. Stay under a comfortable [[threshold]].",
    steps: [
      "Invite your puppy onto a familiar surface and [[reward]].",
      "Place a few treats just onto the edge of a new surface.",
      "Let them choose to step on — never push or drag. Watch [[body-language]] and [[stress-signals]].",
      "Celebrate small steps and finish while they still feel brave. Allow [[recovery-time]] afterwards.",
    ],
    lookFor: "Willing investigation without freezing or rushing away.",
    ifDifficult:
      "Make the new surface smaller, closer to a familiar one, and more heavily rewarded. Increase comfort [[distance]] from anything scary.",
    safetyNote:
      "Avoid slippery or unsafe surfaces. If your puppy seems sore, check with a vet.",
    hint: "Choice builds confidence. Pushing builds worry.",
    glossaryTermIds: [
      "choice-consent",
      "threshold",
      "reward",
      "body-language",
      "stress-signals",
      "recovery-time",
      "distance",
    ],
    topicGroup: "puppy_life",
    contentVersion: 2,
  },
];

export const TOPIC_GROUPS: {
  id: ExerciseContent["topicGroup"];
  title: string;
  description: string;
}[] = [
  {
    id: "everyday_foundations",
    title: "Everyday foundations",
    description: "Attention, name response, and simple manners.",
  },
  {
    id: "puppy_life",
    title: "Puppy life",
    description: "Gentle confidence-building for younger dogs.",
  },
  {
    id: "walking_together",
    title: "Walking together",
    description: "Lead comfort and check-ins on walks.",
  },
  {
    id: "coming_back",
    title: "Coming back when called",
    description: "Recall foundations that feel rewarding.",
  },
  {
    id: "calm_confidence",
    title: "Calm and confidence",
    description: "Settling, handling, and quiet rest.",
  },
  {
    id: "life_at_home",
    title: "Life at home",
    description: "Doorways, greetings, and everyday pauses.",
  },
];

export function getExerciseById(id: string): ExerciseContent | undefined {
  return EXERCISE_LIBRARY.find((exercise) => exercise.id === id);
}
